version: '3.9'

services:
  app:
    image: openjdk:17
    ports:
      - 8080:8080
      - 5050:5050
    tty: true
    command: >
      sh -c "
      microdnf install findutils &&
      ./gradlew clean bootRun
      "
    # command: microdnf install findutils ; ./gradlew clean bootRun
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blanco
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - mysql-network
    volumes:
      - ./db/init/initdb.d:/docker-entrypoint-initdb.d 
      - ./db/data:/var/lib/mysql"
      - ./db/config/my.cnf:/etc/mysql/conf.d/my.cnf
    command: "mysqld"

  dbcli:
    image: mysql:8.0.27
    networks:
      - mysql-network
    command: mysql -hdb -uuser -ppassword blanco

networks:
  mysql-network:
    driver: bridge
