spring:
  security:
    user:
      name: guest
      password: guest
  session:
    redis:
      repository-type: default
    timeout: 180s
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blanco
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  thymeleaf:
    mode: html 
logging:
  file:
    name: classpath:logback.yaml
url:
  localhost: http://localhost:8080