spring:
  security:
    user:
      name: guest
      password: guest
  session:
    redis:
      repository-type: default
    timeout: 180s
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3307/blanco}
    username: root
    password: password
  jpa:
    show-sql: true
  thymeleaf:
    mode: html
logging:
  file:
    name: classpath:logback.yaml
url:
  fqdn: http://localhost:8080